controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_display_message: 
    path: /home/display/message
    controller: App\Controller\HomeController::displayMessage 

